pet_menu:
  feeding_pet_button: "&lFeeding a pet"
  visible_pet_name_button_on: "&lThe pet's name is visible!"
  visible_pet_name_button_off: "&lThe pet's name is hidden!"
  play_with_pet_button_on: "&lPlay"
  play_with_pet_button_off: "&lThe pet doesn't want to play!"
  play_with_pet_button_lore:
    - "&fPoints: %points%/%points_for_next_level%"
    - "&fCurrent level: %level%"
  pet_inventory_slot_lock: "&l&fReach friendship level 5 to unlock this slot."

pet_feeding_menu:
  menu_name: "&lFeed your pet"
  feed_button: "&lFeed it"

messages:
  this_pet_not_tamed: "This pet has not been tamed yet."
  its_not_your_pet: "It's not your pet!"

awards:
  for_level_15:
    name: "&lA loyal friend"
    lore:
      - "&bFor the 10th level of friendship"
  for_level_30:
    name: "&lPet's favorite toy"
    lore:
      - "&bFor the 30th level of friendship"

pet:
  default_name: "%owner_name%`s dog"

setting:
  disable_shulkerbox_in_pet_inventory: true
  pet_play_cooldown: 3600000 #milliseconds (3600000 == 1 hour)
  get_1_health_for_1_friend_level: false